site_name: Workshop data sciences
copyright: "Copyright &copy; 2017 DAPLAB & UNIFR"
site_author: "Lucy Linder (DAPLAB)"


# ----------------------

pages:
    - index.md
    # day 1
    - HDFS: hdfs.md
    - MapReduce: mapreduce.md
    - Hive: hive.md
    # day 2
    - Zeppelin/Spark SQL: zeppelin.md
    - LSA with Spark ML: spark.md 

# ----------------------

theme: 'material' # see https://squidfunk.github.io/mkdocs-material for the documentation

markdown_extensions:
    - footnotes
    - attr_list
    - admonition
    - codehilite #(linenums=true)
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    # - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
#   - mdx_math

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
    - style.css

extra:
    palette:
        primary: 'blue'
        accent: 'orange'
